services:
  cloudfox-api:
    image: cloudfox-api:latest
    container_name: cloudfox-api
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WH_SECRET: ${STRIPE_WH_SECRET}

      AWS_ENDPOINT_OVERRIDE: http://localstack:4566

    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/cloudfox-api/v1/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  cloudfox-ui:
    image: cloudfox-ui:latest
    container_name: cloudfox-ui
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped

    environment:
      SERVICES: s3
      AWS_REGION: ${AWS_REGION}
      DEBUG: "1"

    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:1.27
    container_name: cloudfox-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      cloudfox-api:
        condition: service_healthy
      cloudfox-ui:
        condition: service_started

volumes:
  postgres_data:
  localstack_data: