spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudfox
    username: postgres
    password: 3088
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
stripe:
  secret-key: ${STRIPE_SECRET_KEY}